### ISSUE TITLE
Change Home Page 1

### ISSUE THREAD

**Issue by mcb2605** [BrainConnexion/Change-home-page#1]
Can you use the following tag lines when scrolling through the pictures. "Hire community service providers for services you need", "Don't pay the going rate, pay what you can afford", "Out of work or need extra cash, Bid for services in your community", Receive royalty credits when recommending service providers who do work in your community", "Need A Service - Ask Your Community - Pay Your Price"
![screen shot 2016-10-23 at 10 36 49 pm](https://cloud.githubusercontent.com/assets/22572663/19639458/2df6dfe6-9a0b-11e6-9e39-26f661034525.png)

**Comment by naiduarvind** [comment]
Seems like you are getting a hang of Github. Nice to know you have. Will definitely get on fixing the issues.

**Comment by mcb2605** [comment]
Thank you!  You trained me well😜 How is the sign in hook up going? How did F1 go last night? Too busy to have looked it up!
Cheers,
Jeff

**Comment by naiduarvind** [comment]
Modified home page header title. The transition animation with different header title will be added when the full version of Helptimize goes up live.
