### ISSUE TITLE
Change Home Page Tiles

### ISSUE THREAD

**Issue by mcb2605** [BrainConnexion/Change-home-page#2]
Can you change the home page tiles to the ones on the screen shot below and you can still add Others and Coupons & Tickets.
![screen shot 2016-10-24 at 5 02 21 pm](https://cloud.githubusercontent.com/assets/22572663/19639656/e8640bf6-9a0b-11e6-9288-b7c529e2cd21.png)
![screen shot 2016-10-24 at 4 45 46 pm](https://cloud.githubusercontent.com/assets/22572663/19639684/089b37dc-9a0c-11e6-9c86-61785cd419d5.png)

**Comment by naiduarvind** [comment]
Changes have been made. Please have a look at the main static-product-beta repository.
